const errorScope = {
	bmcplatform: 15000,
	atxplatform: 80000,
	groupsaccessmanager: 111000,
	pendingmanager: 4000,
}

const errorsLibrary = {
	UNAUTHORIZED: 0,
	OK: 1,
	NO_RECORDS_WERE_FOUND: 2,
	MULTISIG_ADDED: 3,
	UNDEFINED: 0xDEFDEFDEF,
	OBJECT_ACCESS_DENIED_CONTRACT_OWNER_ONLY: 8,

	BMC_PLATFORM_PROXY_ALREADY_EXISTS: errorScope.bmcplatform + 0,
	BMC_PLATFORM_CANNOT_APPLY_TO_ONESELF: errorScope.bmcplatform + 1,
	BMC_PLATFORM_INVALID_VALUE: errorScope.bmcplatform + 2,
	BMC_PLATFORM_INSUFFICIENT_BALANCE: errorScope.bmcplatform + 3,
	BMC_PLATFORM_NOT_ENOUGH_ALLOWANCE: errorScope.bmcplatform + 4,
	BMC_PLATFORM_ASSET_ALREADY_ISSUED: errorScope.bmcplatform + 5,
	BMC_PLATFORM_CANNOT_ISSUE_FIXED_ASSET_WITH_INVALID_VALUE: errorScope.bmcplatform + 6,
	BMC_PLATFORM_CANNOT_REISSUE_FIXED_ASSET: errorScope.bmcplatform + 7,
	BMC_PLATFORM_SUPPLY_OVERFLOW: errorScope.bmcplatform + 8,
	BMC_PLATFORM_NOT_ENOUGH_TOKENS: errorScope.bmcplatform + 9,
	BMC_PLATFORM_INVALID_NEW_OWNER: errorScope.bmcplatform + 10,
	BMC_PLATFORM_ALREADY_TRUSTED: errorScope.bmcplatform + 11,
	BMC_PLATFORM_SHOULD_RECOVER_TO_NEW_ADDRESS: errorScope.bmcplatform + 12,
	BMC_PLATFORM_ASSET_IS_NOT_ISSUED: errorScope.bmcplatform + 13,
	BMC_PLATFORM_ACCESS_DENIED_ONLY_OWNER: errorScope.bmcplatform + 14,
	BMC_PLATFORM_ACCESS_DENIED_ONLY_PROXY: errorScope.bmcplatform + 15,
	BMC_PLATFORM_ACCESS_DENIED_ONLY_TRUSTED: errorScope.bmcplatform + 16,
	BMC_PLATFORM_INVALID_INVOCATION: errorScope.bmcplatform + 17,

	ATX_PLATFORM_PROXY_ALREADY_EXISTS: errorScope.atxplatform + 1,
	ATX_PLATFORM_CANNOT_APPLY_TO_ONESELF: errorScope.atxplatform + 2,
	ATX_PLATFORM_INVALID_VALUE: errorScope.atxplatform + 3,
	ATX_PLATFORM_INSUFFICIENT_BALANCE: errorScope.atxplatform + 4,
	ATX_PLATFORM_NOT_ENOUGH_ALLOWANCE: errorScope.atxplatform + 5,
	ATX_PLATFORM_ASSET_ALREADY_ISSUED: errorScope.atxplatform + 6,
	ATX_PLATFORM_CANNOT_ISSUE_FIXED_ASSET_WITH_INVALID_VALUE: errorScope.atxplatform + 7,
	ATX_PLATFORM_CANNOT_REISSUE_FIXED_ASSET: errorScope.atxplatform + 8,
	ATX_PLATFORM_SUPPLY_OVERFLOW: errorScope.atxplatform + 9,
	ATX_PLATFORM_NOT_ENOUGH_TOKENS: errorScope.atxplatform + 10,
	ATX_PLATFORM_INVALID_NEW_OWNER: errorScope.atxplatform + 11,
	ATX_PLATFORM_ALREADY_TRUSTED: errorScope.atxplatform + 11,
	ATX_PLATFORM_SHOULD_RECOVER_TO_NEW_ADDRESS: errorScope.atxplatform + 12,
	ATX_PLATFORM_ASSET_IS_NOT_ISSUED: errorScope.atxplatform + 13,
	ATX_PLATFORM_INVALID_INVOCATION: errorScope.atxplatform + 14,

	USER_MANAGER_MEMBER_ALREADY_EXIST: errorScope.groupsaccessmanager + 1,
	USER_MANAGER_GROUP_ALREADY_EXIST: errorScope.groupsaccessmanager + 2,
	USER_MANAGER_INVALID_INVOCATION: errorScope.groupsaccessmanager + 7,
	USER_MANAGER_DONE: errorScope.groupsaccessmanager + 11,
	USER_MANAGER_CANCELLED: errorScope.groupsaccessmanager + 12,

	PENDING_MANAGER_INVALID_INVOCATION: errorScope.pendingmanager + 1,
	PENDING_MANAGER_HASNT_VOTED: errorScope.pendingmanager + 2,
	PENDING_DUPLICATE_TX: errorScope.pendingmanager + 3,
	PENDING_MANAGER_CONFIRMED: errorScope.pendingmanager + 4,
	PENDING_MANAGER_REJECTED: errorScope.pendingmanager + 5,
	PENDING_MANAGER_IN_PROCESS: errorScope.pendingmanager + 6,
	PENDING_MANAGER_TX_DOESNT_EXIST: errorScope.pendingmanager + 7,
	PENDING_MANAGER_TX_WAS_DECLINED: errorScope.pendingmanager + 8,
	PENDING_MANAGER_TX_WAS_NOT_CONFIRMED: errorScope.pendingmanager + 9,
	PENDING_MANAGER_INSUFFICIENT_GAS: errorScope.pendingmanager + 10,
	PENDING_MANAGER_POLICY_NOT_FOUND: errorScope.pendingmanager + 11,

}

module.exports = errorsLibrary
